services:
    master:
        image: caobaoqi1029/big-data-single:0.1.0
        container_name: master
        hostname: master
        ports:
            - "9870:9870"
            - "9000:9000"
        command: bash -c "
            service ssh restart &&
            tail -f /dev/null"
        volumes:
            - ~/.m2:/root/.m2
        networks:
            - hadoop-network
        depends_on:
            - db

    db:
        image: mysql:5.7
        container_name: db
        hostname: db
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - hadoop-network
networks:
    hadoop-network:
        driver: bridge
